### ISSUE TITLE
Ashish Verma-ashishodu2023

### ISSUE THREAD

**Issue by ashishodu2023** [odu-cs625-datavis/public-fall24-mcw#3]
Hello Professor,

Please find the details below

- GitHub =>https://github.com/ashishodu2023

- Observable =>https://observablehq.com/user/@ashishodu2023

Thanks,
Ashish

**Comment by weiglemc** [comment]
Please follow the given instructions on how to submit the issue:
"The title should be your name and your GitHub username. You should see my example in the list of Issues."

In addition, your Observable username needs to be the same as your GitHub username since you are creating an Observable account with your GitHub credentials. If there's some reason this doesn't work, let me know.

**Comment by ashishodu2023** [comment]
Hello Professor,

Made necessary changes.

Thanks,
Ashish

**Comment by NAVYAOGIRALA** [comment]
Repo Created : https://github.com/odu-cs625-datavis/fall24-mcw-ashishodu2023
